# Generated by Django 5.1.6 on 2025-02-23 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ferramentas/')),
            ],
        ),
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('dados', models.JSONField(default=dict)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_criadas', to=settings.AUTH_USER_MODEL)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='metodologia.ferramenta')),
                ('participantes', models.ManyToManyField(blank=True, related_name='instancias_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='metodologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='metodologia.metodologia'),
        ),
        migrations.CreateModel(
            name='PDCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.TextField(verbose_name='Plano (Plan)')),
                ('execucao', models.TextField(blank=True, null=True, verbose_name='Execução (Do)')),
                ('verificacao', models.TextField(blank=True, null=True, verbose_name='Verificação (Check)')),
                ('acao', models.TextField(blank=True, null=True, verbose_name='Ação (Act)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdcas', to='metodologia.ferramenta')),
            ],
        ),
    ]
