# Generated by Django 5.1.6 on 2025-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='metodologia',
            options={'ordering': ['nome'], 'verbose_name': 'metodologia', 'verbose_name_plural': 'metodologias'},
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodologia',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ferramenta',
            index=models.Index(fields=['id', 'slug'], name='metodologia_id_fecfca_idx'),
        ),
        migrations.AddIndex(
            model_name='ferramenta',
            index=models.Index(fields=['nome'], name='metodologia_nome_97324e_idx'),
        ),
        migrations.AddIndex(
            model_name='metodologia',
            index=models.Index(fields=['nome'], name='metodologia_nome_80ef7c_idx'),
        ),
    ]
