# Generated by Django 5.1.6 on 2025-02-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0002_alter_ferramenta_options_alter_metodologia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
