# Generated by Django 5.1.6 on 2025-02-23 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0003_alter_ferramenta_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdca',
            name='dono',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='pdcas_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
