# Generated by Django 5.1.6 on 2025-02-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0004_pdca_dono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='ferramentas_participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instanciaferramenta',
            name='pdca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancia', to='metodologia.pdca'),
        ),
        migrations.AlterField(
            model_name='pdca',
            name='dono',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='pdcas_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
