# Generated by Django 5.1.6 on 2025-02-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0005_ferramenta_participantes_instanciaferramenta_pdca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciaferramenta',
            name='pdca',
        ),
        migrations.AddField(
            model_name='pdca',
            name='instancia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdca', to='metodologia.instanciaferramenta'),
        ),
    ]
